services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: warp-backend
    depends_on:
      - ollama
    ports:
      - "3030:3030"
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: warp-frontend
    depends_on:
      - backend
    ports:
      - "3005:3000"


volumes:
  ollama_data:
